### ISSUE TITLE
Crash at black screen when selecting a game too fast

### ISSUE THREAD

**Issue by ToppestOfDogs** [dimok789/loadiine_gx2#1] opened 2016-02-06 02:21 UTC
If you don't wait for the carousel on the tv to finish it's animation (Switch games and immediately press A) it won't load a game, it'll freeze on a black screen.
Example: Highlight game A, press right to highlight game B, press A while the screen still says "Game A", the system will freeze.

**Comment by dimok789** [comment] 2016-02-06 07:29
Ok thanks. I will have to look at it later.

**Comment by scuba156** [comment] 2016-02-12 04:38
Cannot reproduce on 5.4.0EUR on either the cover or icon carousel. Switching game and pressing A immediately will show the previously selected item on screen but still boots to the game in the target position which is the correct behaviour.

Can anybody else reproduce?

**Comment by dimok789** [comment] 2016-02-12 15:11
Yeah I have the same behaviour as scuba156. Can you maybe describe the process you do step by step and be as detailed as possible?

**Comment by ToppestOfDogs** [comment] 2016-02-12 15:55
That's about as detailed as it gets, it's probably just a problem on my end if no one else can make it happen.
But it is a 5.4 USA 32gb console, if that matters at all.

**Comment by dimok789** [comment] 2016-02-12 16:07
No that actually doesnt matter.

I will try playing around with it a bit and look at the source part of it. Maybe I will eventually hit that crash/issue.

**Comment by dimok789** [comment] 2016-04-16 06:59
fixed on last commit

**Closed by dimok789** 2016-04-16 06:59 UTC
